### ISSUE TITLE
ProTECT requires bd2k-python-lib==1.14a1 but s3am requires bd2k-python-lib==1.13.dev.16

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/protect#132]
ProTECT requires both s3am and bd2k-python-lib. `s3am==latest` requires `bd2k-python-lib==1.13.dev.16` but ProTECT requires `bd2k-python-lib==1.14a1` which includes `bd2k.util.exceptions.require`.

```
$ ProTECT --generate_config
Traceback (most recent call last):
  File "/Users/natan/Projects/protect/venv/bin/ProTECT", line 11, in <module>
    load_entry_point('protect', 'console_scripts', 'ProTECT')()
  File "/Users/natan/Projects/protect/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/natan/Projects/protect/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/Users/natan/Projects/protect/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/Users/natan/Projects/protect/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/natan/Projects/protect/src/protect/pipeline/ProTECT.py", line 33, in <module>
    from protect.alignment.dna import align_dna
  File "/Users/natan/Projects/protect/src/protect/alignment/dna.py", line 19, in <module>
    from toil.job import PromisedRequirement
  File "/Users/natan/Projects/protect/venv/lib/python2.7/site-packages/toil/job.py", line 39, in <module>
    from toil.resource import ModuleDescriptor
  File "/Users/natan/Projects/protect/venv/lib/python2.7/site-packages/toil/resource.py", line 34, in <module>
    from bd2k.util.exceptions import require
ImportError: cannot import name require
```

**Comment by natanlao** [comment]
`s3am` will work with the newer version of `bd2k-python-lib`, so it's acceptable to remove the version of `bd2k-python-lib` installed as `s3am`'s dependency and install `bd2k-python-lib==1.14a1` in its place.

**Comment by arkal** [comment]
Can i close this? This is a Toil issue.
