### ISSUE TITLE
"No Locks Available" error

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/protect#70]
```
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:  ---TOIL WORKER OUTPUT LOG---
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:  WARNING:toil.resource:The localize() method should only be invoked on a worker.
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:  WARNING:toil.resource:Can't find resource for leader path '/neoantigen_prediction/protect/src/protect'
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:  WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/neoantigen_prediction/protect/src', name='protect.pipeline.ProTECT')
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:  CRITICAL:toil.job:CACHE: Unable to acquire lock on /mnt/isilon/maris_lab/target_nbl_ngs/Eric/neoantigen_prediction/test_outputs/toil-64121748-44a6-4d46-bbb4-b0216cfdcd85/cache-64121748-44a6-4d46-bbb4-b0216cfdcd85/.cacheLock
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:  Traceback (most recent call last):
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:    File "/neoantigen_prediction/protect/venv/lib/python2.7/site-packages/toil/worker.py", line 330, in main
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,112 WARNING: toil.leader: K/p/job1Qif4A:      fileStore = FileStore(jobStore, jobWrapper, localWorkerTempDir, blockFn)
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:    File "/neoantigen_prediction/protect/venv/lib/python2.7/site-packages/toil/job.py", line 995, in __init__
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:      self._setupCache()
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:    File "/neoantigen_prediction/protect/venv/lib/python2.7/site-packages/toil/job.py", line 1469, in _setupCache
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:      with self._CacheState.open(self) as cacheInfo:
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:    File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:      return self.gen.next()
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:    File "/neoantigen_prediction/protect/venv/lib/python2.7/site-packages/toil/job.py", line 1826, in open
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:      with outer.cacheLock():
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:    File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:      return self.gen.next()
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,113 WARNING: toil.leader: K/p/job1Qif4A:    File "/neoantigen_prediction/protect/venv/lib/python2.7/site-packages/toil/job.py", line 1433, in cacheLock
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,114 WARNING: toil.leader: K/p/job1Qif4A:      flock(cacheLockFile, LOCK_EX)
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,114 WARNING: toil.leader: K/p/job1Qif4A:  IOError: [Errno 37] No locks available
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,114 WARNING: toil.leader: K/p/job1Qif4A:  Exiting the worker because of a failed jobWrapper on host reslnmarisig01.research.chop.edu
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,114 WARNING: toil.leader: K/p/job1Qif4A:  ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host reslnmarisig01.research.chop.edu
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,114 WARNING: toil.leader: K/p/job1Qif4A:  WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job K/p/job1Qif4A to 0
reslnmarisig01.research.chop.edu: 2016-07-01 11:31:46,114 WARNING: toil.leader: Job: K/p/job1Qif4A is completely failed
```

@hannes-ucsc any comments?

**Comment by arkal** [comment]
More data from eric

```
(venv) [sanforde@reslnmarisig01 test_outputs]$ df -T /mnt/isilon/maris_lab/target_nbl_ngs/Eric/neoantigen_prediction/test_outputs/
Filesystem                                                            Type    1K-blocks         Used   Available Use% Mounted on
resisns01.research.chop.edu:/ifs/data/groups/maris_lab/target_nbl_ngs nfs  161061273600 125610468352 35450805248  78% /mnt/isilon/maris_lab/target_nbl_ngs


df -ah output
(venv) [sanforde@reslnmarisig01 test_outputs]$ df -ah
Filesystem                                                             Size  Used Avail Use% Mounted on
rootfs                                                                    -     -     -    - /
sysfs                                                                     0     0     0    - /sys
proc                                                                      0     0     0    - /proc
devtmpfs                                                                24G     0   24G   0% /dev
securityfs                                                                0     0     0    - /sys/kernel/security
tmpfs                                                                   24G     0   24G   0% /dev/shm
devpts                                                                    0     0     0    - /dev/pts
tmpfs                                                                   24G   17M   24G   1% /run
tmpfs                                                                   24G     0   24G   0% /sys/fs/cgroup
cgroup                                                                    0     0     0    - /sys/fs/cgroup/systemd
pstore                                                                    0     0     0    - /sys/fs/pstore
cgroup                                                                    0     0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                                                                    0     0     0    - /sys/fs/cgroup/memory
cgroup                                                                    0     0     0    - /sys/fs/cgroup/perf_event
cgroup                                                                    0     0     0    - /sys/fs/cgroup/blkio
cgroup                                                                    0     0     0    - /sys/fs/cgroup/devices
cgroup                                                                    0     0     0    - /sys/fs/cgroup/cpuset
cgroup                                                                    0     0     0    - /sys/fs/cgroup/freezer
cgroup                                                                    0     0     0    - /sys/fs/cgroup/hugetlb
cgroup                                                                    0     0     0    - /sys/fs/cgroup/net_cls
configfs                                                                  0     0     0    - /sys/kernel/config
/dev/mapper/rootvg-lv_root                                              15G  4.1G   11G  27% /
selinuxfs                                                                 0     0     0    - /sys/fs/selinux
systemd-1                                                                 -     -     -    - /proc/sys/fs/binfmt_misc
mqueue                                                                    0     0     0    - /dev/mqueue
hugetlbfs                                                                 0     0     0    - /dev/hugepages
debugfs                                                                   0     0     0    - /sys/kernel/debug
nfsd                                                                      0     0     0    - /proc/fs/nfsd
/dev/mapper/datavg-lv_data                                              80G   33M   80G   1% /data
/dev/sda1                                                             1008M  139M  819M  15% /boot
/dev/mapper/rootvg-lv_tmp                                              3.0G   33M  3.0G   2% /tmp
/dev/mapper/rootvg-lv_home                                              10G  729M  9.3G   8% /home
/dev/mapper/rootvg-lv_var                                              8.0G  1.9G  6.2G  24% /var
sunrpc                                                                    0     0     0    - /var/lib/nfs/rpc_pipefs
/dev/mapper/rootvg-lv_audit                                           1014M   96M  919M  10% /var/log/audit
resisns01.research.chop.edu:/ifs/data/groups/maris_lab/target_nbl_ngs  150T  117T   34T  78% /mnt/isilon/maris_lab/target_nbl_ngs
binfmt_misc                                                               0     0     0    - /proc/sys/fs/binfmt_misc
```

**Comment by hannes-ucsc** [comment]
What type of file system is on /mnt/isilon?

The local workflow directory should not be on a network file system.

@arkal, for users who are forced to use a network file system, is there a way to completely disable caching?

**Comment by arkal** [comment]
not anymore lol

**Comment by hannes-ucsc** [comment]
Well, the old way of disabling the new caching was switching to the old FileStore implementation which had the ballast of the background writing. Can you think of a way to disable caching by switching to a dummy FileStore implementation that does no caching and no asynchronous writing?

We might also want to think about not using flock(), but instead using Sys-V semaphores or using flock() on shadow files.

**Comment by arkal** [comment]
Depends on BD2KGenomics/toil/issues/1072
